[tool.black]
line-length = 127
preview = true

[tool.isort]
profile = "black"
line_length = 127
known_third_party = ["rdwv"]

[tool.pytest.ini_options]
addopts = ["-n", "auto", "--cov=.", "--cov-report", "term-missing"]
filterwarnings = [
    "error::DeprecationWarning",
    "error::PendingDeprecationWarning",
    "ignore:Deprecated call to `pkg_resources.declare_namespace:DeprecationWarning",
    "ignore:pkg_resources is deprecated as an API:DeprecationWarning",               # sqlalchemy
]
norecursedirs = ["tests/functional"]

[tool.coverage.run]
source = ["."]
omit = [
    "main.py",
    "worker.py",
    "alembic/**",
    "settings/**",
    "tests/**",
    "modules/**",
    "venv/**",
    "env/**",
    "api/ext/update.py",
    "api/ext/configurator.py",
    "api/ext/backups.py",
    "api/ext/shopify.py",
    "api/ext/payouts.py",
    "api/views/stores/integrations/shopify.py",
    "api/logger.py",
    "api/logserver.py",
    "api/invoices.py",
    "api/plugins.py",
    "api/tasks.py",
    "api/settings.py",
    "*__init__.py",
    # TODO: try to have tests for plugins somehow later
    "api/views/plugins.py",
    "api/ext/plugins.py",
    "api/ext/exchanges/**",
    "api/ext/fxrate.py",
]
